document.write( '<body> <nav class=\"navbar navbar-expand-lg fixed-top\">\n' );
document.write( '<div class=\"navbar-brand brand\" href=\"/\">\n' );
document.write( '<a href=\"index.html\">\n' );
document.write( '<img src=\"img/logo.svg\" width=\"30\" height=\"30\" class=\"d-inline-block align-top\" alt=\"\" style=\"margin-right:10px;\"> Book Bin\n' );
document.write( '</a>\n' );
document.write( '</div>\n' );
document.write( '<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n' );
document.write( '<span class=\"navbar-toggler-icon\"></span>\n' );
document.write( '</button>\n' );
document.write( '<input class=\"form-control search\" type=\"text\" placeholder=\"Search\" aria-label=\"Search\">\n' );
document.write( '<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n' );
document.write( '<ul class=\"navbar-nav mr-auto\">\n' );
document.write( '<li class=\"nav-item active\">\n' );
document.write( '<a class=\"nav\" href=\"cart.html\" style=\"cursor: pointer;\">Cart<span class=\"sr-only\">(current)</span></a>\n' );
document.write( '</li>\n' );
document.write( '<li class=\"nav-item active\">\n' );
document.write( '<a class=\"nav\" href=\"account.html\" style=\"cursor: pointer;\">Account<span class=\"sr-only\">(current)</span></a>\n' );
document.write( '</li>\n' );
document.write( '</ul>\n' );
document.write( '</div>\n' );
document.write( '</nav>\n' );
document.write( '</body>' );
